# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1474592442);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1474591962);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1474606122);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 1474592202);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1474592322);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1474591842);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1474592082);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/root/page/a");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.migration.version", 31);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "MX");
user_pref("browser.search.region", "MX");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160107230306");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1458005519202");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1457919186647");
user_pref("datareporting.policy.firstRunTime", "1457919119202");
user_pref("datareporting.sessions.current.activeTicks", 10);
user_pref("datareporting.sessions.current.firstPaint", 5331);
user_pref("datareporting.sessions.current.main", 157);
user_pref("datareporting.sessions.current.sessionRestored", 5708);
user_pref("datareporting.sessions.current.startTime", "1477010716511");
user_pref("datareporting.sessions.current.totalTime", 55);
user_pref("datareporting.sessions.currentIndex", 24);
user_pref("datareporting.sessions.previous.22", "{\"s\":1477008703036,\"a\":6,\"t\":75,\"c\":true,\"m\":1027,\"fp\":22752,\"sr\":26983}");
user_pref("datareporting.sessions.previous.23", "{\"s\":1477008961268,\"a\":6,\"t\":32,\"c\":true,\"m\":60,\"fp\":2584,\"sr\":2629}");
user_pref("datareporting.sessions.prunedIndex", 21);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 7);
user_pref("extensions.blocklist.pingCountVersion", 7);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:43.0.4");
user_pref("extensions.getAddons.cache.lastUpdate", 1474592443);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "43.0.4");
user_pref("extensions.lastPlatformVersion", "43.0.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"43.0.4\",\"st\":1457915839000,\"mt\":1452216977000}}}");
user_pref("gecko.buildID", "20160107230306");
user_pref("gecko.mstone", "43.0.4");
user_pref("idle.lastDailyNotification", 1477010822);
user_pref("media.gmp-manager.buildID", "20160107230306");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1474591742);
user_pref("places.history.expiration.transient_current_max_pages", 80108);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1474591742);
user_pref("toolkit.startup.last_success", 1477010716);
user_pref("toolkit.telemetry.cachedClientID", "e9520704-a222-4e00-8bf4-c18eaf79e77a");
user_pref("toolkit.telemetry.previousBuildID", "20160107230306");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
